version = 0.1

[default.deploy.parameters]
stack_name = "dynamic-dns-stack"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "us-east-2"
